root: true
extends: standard
parserOptions:
  ecmaVersion: 2017
plugins:
  - node
  - standard
  - jest
env:
  browser: false
  es6: true
  jest: true
  node: true
rules:
  node/no-unsupported-features:
    - error
    - { version: 6 }
  semi:
    - error
    - always
  padded-blocks:
    - error
    - { switches: always, classes: always }
  space-before-function-paren:
    - error
    - { anonymous: always, named: never }
  no-unused-vars:
    - warn
    - { vars: all, args: none }
  # newline-per-chained-call:       # this won't work with prettier
  #   - error
  #   - { ignoreChainWithDepth: 2 }
